library(Deriv)
library(stringr)
##A file to create the file R/seird_Methods_NthDeriv.R
#which derivatives to include
nderivs <- seq(3,11)
#write the preamble code
codeStart <- c(
  "### !!! THIS FILE GENERATED BY Make_seird_Methods_NthDeriv.R, DO NOT EDIT BY HAND !!! ###",
  "#' A function that returns a function to calculate the n-derivative of D for",
  "#' an SEIRD model",
  "#' @noRd",
  "setMethod('getNthDeriv', signature('seirdModel'),",
  "function(epiModel, nderiv){")
codeEnd <- c(
  "else{deriv <- NA}",
  "return(deriv)",
  "})"
)
#set up model to compile
Sf <- function(t){S}
Df <- function(t){D}
Rf <- function(t){R}
If <- function(t){I}
Ef <- function(t){E}
#setup derivatives
drule <- Deriv::drule #a copy of the derivative rules from Deriv
drule[["Sf"]] <-alist(t=-Beta*If(t)*Sf(t)/N)
drule[["Ef"]] <-alist(t=Beta*If(t)*Sf(t)/N - Lambda*Ef(t))
drule[["If"]] <-alist(t=Lambda*Ef(t) - (Alpha + Gamma)*If(t))
drule[["Df"]] <-alist(t=Alpha*If(t))
drule[["Rf"]] <-alist(t=Gamma*If(t))
#use Deriv to calculate nth derivative
derivFunc <- Deriv(Df, "t", nderiv = nderivs[1]-1, drule=drule)
#loop through iteratively using the previous derivFunc, calculated
derivCodes <- c()
for(nderivIndex in seq.int(nderivs)){
  nderiv <- nderivs[nderivIndex]
  #get deriv function
  derivFunc <- Deriv(derivFunc, "t", nderiv = 1, drule=drule)
  #adjust formals
  derivFuncCopy <- derivFunc
  formals(derivFuncCopy) <- alist(epiModel = , I = )
  #get code
  derivCode <- deparse(derivFuncCopy)

  #add a line of code to calculate Beta
  derivCode <- c(derivCode[1:2],
                 "Beta <- epiModel@parameters$Betas[whichIndex(epiModel@currentState$t, epiModel@parameters$changeTimes)]",
                 derivCode[3:length(derivCode)])

  if(nderivIndex == 1){
    #if the first set up if statement
    derivCode <- c(paste0("if(nderiv==", nderiv, "){"), derivCode)
  }
  else{
    #else and else if statemtent
    derivCode <- c(paste0("else if(nderiv==", nderiv, "){"), derivCode)
  }
  #add assignment to deriv
  derivCode[2] <- paste0("deriv <- ", derivCode[2])
  #add final bracket
  derivCode[length(derivCode) + 1] <- "}"
  #add to code
  derivCodes <- c(derivCodes, derivCode)
}

#replacing functions with values
derivCodes <- str_replace_all(derivCodes, "If\\(t\\)", "I")
derivCodes <- str_replace_all(derivCodes, "Ef\\(t\\)", "(N - epiModel@currentState$S - epiModel@currentState$D - epiModel@currentState$R - I)")
derivCodes <- str_replace_all(derivCodes, "Sf\\(t\\)", "epiModel@currentState$S")
derivCodes <- str_replace_all(derivCodes, "N", "epiModel@initialState$N")
#replace all parameters etc with calls to the relevant slot
for(parameter in c("Lambda","Alpha","Gamma")){
  derivCodes <- stringr::str_replace_all(derivCodes, parameter,
                                        paste0("epiModel@parameters$",parameter))
}

#add deriv code to main code
code <- c(codeStart, derivCodes, codeEnd)
#write to file
writeLines(code, con = "R/seird_Methods_NthDeriv.R")
#empty enviroment
rm(list=c("drule","code","codeEnd","codeStart","derivCode","derivCodes","nderiv",
          "nderivIndex","nderivs","parameter","derivFunc","derivFuncCopy","Df",
          "Ef","If","Rf","Sf"))
