## Automatically generated by odin - do not edit
.sirdGenerator <- odin:::odin_c_class("sirdGenerator", list(get_internal = "sirdGenerator_get_internal", finalise = "sirdGenerator_finalise", create = "sirdGenerator_create", initmod_desolve = "sirdGenerator_initmod_desolve", contents = "sirdGenerator_contents", set_user = "sirdGenerator_set_user", metadata = "sirdGenerator_metadata", initial_conditions = "sirdGenerator_initial_conditions", rhs = "sirdGenerator_rhs", rhs_dde = "sirdGenerator_rhs_dde", rhs_desolve = "sirdGenerator_rhs_desolve", output = "sirdGenerator_output_dde", rhs_r = "sirdGenerator_rhs_r"), c("Alpha", "Betas", "changeTimes", "Gamma", "I0", "S0", "D0", "R0"), list(discrete = FALSE, has_array = TRUE, has_output = TRUE, has_user = TRUE, has_delay = FALSE, has_interpolate = TRUE, has_stochastic = FALSE, has_include = FALSE, initial_time_dependent = FALSE), "excalibur", "odin/sirdGenerator.json", TRUE)
sirdGenerator <- structure(function (Alpha, Betas, changeTimes, Gamma, I0, S0,
    D0 = NULL, R0 = NULL, user = list(Alpha = Alpha, Betas = Betas,
        changeTimes = changeTimes, Gamma = Gamma, I0 = I0, S0 = S0,
        D0 = D0, R0 = R0), unused_user_action = NULL, use_dde = FALSE)
{
    .sirdGenerator$new(user, unused_user_action, use_dde)
}, ir = "odin/sirdGenerator.json", class = "odin_generator")
class(sirdGenerator) <- "odin_generator"
attr(sirdGenerator, "ir") <- .sirdGenerator$public_fields$ir
