## Automatically generated by odin - do not edit
.sirGenerator <- odin:::odin_c_class("sirGenerator", list(get_internal = "sirGenerator_get_internal", finalise = "sirGenerator_finalise", create = "sirGenerator_create", initmod_desolve = "sirGenerator_initmod_desolve", contents = "sirGenerator_contents", set_user = "sirGenerator_set_user", metadata = "sirGenerator_metadata", initial_conditions = "sirGenerator_initial_conditions", rhs = "sirGenerator_rhs", rhs_dde = "sirGenerator_rhs_dde", rhs_desolve = "sirGenerator_rhs_desolve", output = "sirGenerator_output_dde", rhs_r = "sirGenerator_rhs_r"), c("betas", "ct", "gamma", "I0", "N", "pDeath"), list(discrete = FALSE, has_array = TRUE, has_output = TRUE, has_user = TRUE, has_delay = FALSE, has_interpolate = TRUE, has_stochastic = FALSE, has_include = FALSE, initial_time_dependent = FALSE), "excalibur", "odin/sirGenerator.json", TRUE)
sirGenerator <- structure(function (betas, ct, gamma, I0, N, pDeath, user = list(betas = betas,
    ct = ct, gamma = gamma, I0 = I0, N = N, pDeath = pDeath),
    unused_user_action = NULL, use_dde = FALSE)
{
    .sirGenerator$new(user, unused_user_action, use_dde)
}, ir = "odin/sirGenerator.json", class = "odin_generator")
class(sirGenerator) <- "odin_generator"
attr(sirGenerator, "ir") <- .sirGenerator$public_fields$ir
