#' An S4 method to estimate current state of S, E and I for an SIRD when provided
#' with a total count of deaths so far
#'
#' Please note that this method does not guarantee that this state would be
#' generated by the model, given its initial conditions.
#' This method also makes the assumption that the third derivative of D + R with
#' respect to time is 0.
#' Due to rounding etc, when the value of I would be very small the esimated I
#' will be quite different from the one generated when the model is simulated.
#' At the present time-varying Betas are only partially adjusted for.
#' These values are then stored in the list in the slot "currentState".
#'
#' @param epiModel The epidemic model of class SEIRD to have the current state of
#' S and I estimated.
#' @param deaths The total death count for this model, up to each of the
#' changeTimes so far.
#' @return An object of class seirdModel with the values for S, E and I updated
#' for the current state.
#' @examples
#' #create example model
#' model <- setSEIRD(N = 100, Beta = 1, Lambda = 1, Gamma = 1/5, ProbOfDeath = 0.5, I0 = 1)
#' #Set the deaths (only one entry is required)
#' deaths <- 20
#' #Set the time, makes no difference to this calculation, only used for simulate
#' time <- 10
#' #call this + the D+R node function
#' model <- calculateCurrentState(model, time, deaths)
#'
#' #check S and I
#' currentState(model)
#'
#' #model with time-varying Beta
#' model <- setSEIRD(N = 100, Beta = c(2,1/2), Lambda = 1, Gamma = 1/5, ProbOfDeath = 0.5,
#'  I0 = 1, changeTimes = 5)
#' #Set the deaths, two entries are required now
#' deaths <- c(20,30)
#' time <- 10
#' #the model assumes that the first number 20 is the number of deaths up to the
#' #specified change time 5, and that the last number 30 is the number of deaths
#' #up to the current time (10).
#' #if the current state is not past 5, then we would set deaths <- c(20,20)
#'
#' #call this + the D+R node function
#' model <- calculateCurrentState(model, t=time, deaths=deaths)
#'
#' #check S and I
#' currentState(model)
#'
#' @export
setMethod("estimateInfectiousNode", signature("seirdModel"),
          function(epiModel, deaths){
            #call the SIRD method
            epiModel <- selectMethod(estimateInfectiousNode, "sirdModel")(
              epiModel,
              deaths
            )
            #get model parameters
            Alpha <- epiModel@parameters$Alpha
            Lambda <- epiModel@parameters$Lambda
            Gamma <- epiModel@parameters$Gamma
            Beta <- epiModel@parameters$Betas
            changeTimes <- epiModel@parameters$changeTimes
            S0 <- epiModel@initialState$S0
            I0 <- epiModel@initialState$I0
            S <- epiModel@currentState$S
            D <- epiModel@currentState$D
            R <- epiModel@currentState$R
            N <- Reduce('+', epiModel@initialState)
            #split current value of I between E and I
            I <- I0 - Lambda*(S - S0) + (Lambda*(Alpha + Gamma)*N/tail(Beta, 1))*
              log(S/S0)
            E <- N - I - S - D - R
            #assign
            epiModel@currentState$E <- E
            epiModel@currentState$I <- I
            return(epiModel)
          }
)
