### !!! THIS FILE GENERATED BY Make_seird_Methods_NthDeriv.R, DO NOT EDIT BY HAND !!! ###
#' A function that returns a function to calculate the n-derivative of D for
#' an SEIRD model
#' @noRd
setMethod('getNthDeriv', signature('seirdModel'),
function(epiModel, nderiv){
if(nderiv==3){
deriv <- function (epiModel, I) 
{
Beta <- epiModel@parameters$Betas[whichIndex(epiModel@currentState$t, epiModel@parameters$changeTimes)]
    .e1 <- epiModel@parameters$Alpha + epiModel@parameters$Gamma
    .e3 <- I
    .e4 <- epiModel@parameters$Lambda * (epiModel@initialState$N - epiModel@currentState$S - epiModel@currentState$D - epiModel@currentState$R - I)
    epiModel@parameters$Alpha * (epiModel@parameters$Lambda * (Beta * .e3 * epiModel@currentState$S/epiModel@initialState$N - .e4) - .e1 * (.e4 - 
        .e1 * .e3))
}
}
else if(nderiv==4){
deriv <- function (epiModel, I) 
{
Beta <- epiModel@parameters$Betas[whichIndex(epiModel@currentState$t, epiModel@parameters$changeTimes)]
    .e1 <- I
    .e3 <- epiModel@parameters$Lambda * (epiModel@initialState$N - epiModel@currentState$S - epiModel@currentState$D - epiModel@currentState$R - I)
    .e4 <- epiModel@parameters$Alpha + epiModel@parameters$Gamma
    .e5 <- Beta * .e1
    .e6 <- epiModel@currentState$S
    .e10 <- epiModel@parameters$Lambda * (.e5 * .e6/epiModel@initialState$N - .e3)
    epiModel@parameters$Alpha * (epiModel@parameters$Lambda * (Beta * (.e3 - (epiModel@parameters$Alpha + .e5/epiModel@initialState$N + epiModel@parameters$Gamma) * 
        .e1) * .e6/epiModel@initialState$N - .e10) - .e4 * (.e10 - .e4 * (.e3 - .e4 * 
        .e1)))
}
}
else if(nderiv==5){
deriv <- function (epiModel, I) 
{
Beta <- epiModel@parameters$Betas[whichIndex(epiModel@currentState$t, epiModel@parameters$changeTimes)]
    .e1 <- I
    .e2 <- Beta * .e1
    .e4 <- epiModel@parameters$Lambda * (epiModel@initialState$N - epiModel@currentState$S - epiModel@currentState$D - epiModel@currentState$R - I)
    .e5 <- epiModel@currentState$S
    .e6 <- epiModel@parameters$Alpha + epiModel@parameters$Gamma
    .e10 <- .e2/epiModel@initialState$N
    .e11 <- epiModel@parameters$Lambda * (.e2 * .e5/epiModel@initialState$N - .e4)
    .e13 <- .e4 - (epiModel@parameters$Alpha + .e10 + epiModel@parameters$Gamma) * .e1
    .e19 <- epiModel@parameters$Lambda * (Beta * .e13 * .e5/epiModel@initialState$N - .e11)
    .e20 <- .e4 - .e6 * .e1
    epiModel@parameters$Alpha * (epiModel@parameters$Lambda * (Beta * (.e11 - ((2 * .e10 + epiModel@parameters$Alpha + epiModel@parameters$Gamma) * 
        .e20 + .e2 * .e13/epiModel@initialState$N)) * .e5/epiModel@initialState$N - .e19) - .e6 * (.e19 - 
        .e6 * (.e11 - .e6 * .e20)))
}
}
else if(nderiv==6){
deriv <- function (epiModel, I) 
{
Beta <- epiModel@parameters$Betas[whichIndex(epiModel@currentState$t, epiModel@parameters$changeTimes)]
    .e1 <- I
    .e2 <- Beta * .e1
    .e4 <- epiModel@parameters$Lambda * (epiModel@initialState$N - epiModel@currentState$S - epiModel@currentState$D - epiModel@currentState$R - I)
    .e5 <- epiModel@currentState$S
    .e6 <- epiModel@parameters$Alpha + epiModel@parameters$Gamma
    .e7 <- .e2/epiModel@initialState$N
    .e11 <- epiModel@parameters$Lambda * (.e2 * .e5/epiModel@initialState$N - .e4)
    .e12 <- (epiModel@parameters$Alpha + .e7 + epiModel@parameters$Gamma) * .e1
    .e14 <- .e4 - .e12
    .e15 <- .e4 - .e6 * .e1
    .e18 <- 2 * .e7 + epiModel@parameters$Alpha + epiModel@parameters$Gamma
    .e23 <- epiModel@parameters$Lambda * (Beta * .e14 * .e5/epiModel@initialState$N - .e11)
    .e24 <- .e18 * .e15
    .e26 <- .e2 * .e14/epiModel@initialState$N
    .e33 <- epiModel@parameters$Lambda * (Beta * (.e11 - (.e24 + .e26)) * .e5/epiModel@initialState$N - 
        .e23)
    .e34 <- .e11 - .e6 * .e15
    epiModel@parameters$Alpha * (epiModel@parameters$Lambda * (Beta * (.e23 - (.e18 * .e34 + Beta * ((2 * 
        .e11 - (2 * .e24 + .e26)) * .e1 + (2 * .e15 + .e4 - .e12) * 
        .e15)/epiModel@initialState$N)) * .e5/epiModel@initialState$N - .e33) - .e6 * (.e33 - .e6 * (.e23 - 
        .e6 * .e34)))
}
}
else{deriv <- NA}
return(deriv)
})
