#' An S4 method to calculate current state of R and D for an SIR when provided
#' with a time-series of deaths
#'
#' Please note that this method does not guarantee that this state would be
#' generated by the model, given its initial conditions.
#' Calculates the number of people in the recovered state by scaling D by the
#' rate of recovery divided by the rate of death.
#' These values are then stored in the list in the slot "currentState".
#'
#' @param epiModel The epidemic model of class SIR to have the current state of
#' R and D calculated.
#' @param deaths A time-series of the cumulative death counts for this model.
#' @return An object of class sirModel with the values for D and R updated
#' for the current state.
#' @examples
#' #create example model
#' model <- setSIR(N = 100, Beta = 1, Gamma = 1/5, ProbOfDeath = 0.5, I0 = 1)
#' #Set the deaths (only one entry is required)
#' deaths <- c(10,20)
#' #call this function
#' model <- excalibur::calculateDownstreamExponentialNodes(model, deaths=deaths)
#'
#' print(model@currentState$D)
#' print(model@currentState$R)
#' @export
setMethod("calculateDownstreamExponentialNodes", signature("sirModel"),
          function(epiModel, deaths){
            totalDeaths <- deaths[length(deaths)]
            #checking deaths are in the correct format
            if(any(deaths > totalDeaths) |
               !is.numeric(deaths)){
              stop("deaths must be a numeric timeseries of the cumulative number of
                   deaths. The time between each update should be the unit time
                   for the parameters.")
            }
            #checking there are not more deaths than people in model
            if(totalDeaths > epiModel@odinModel$contents()$S0 +
               epiModel@odinModel$contents()$I0 +
               epiModel@odinModel$contents()$R0 +
               epiModel@odinModel$contents()$D0){
              stop("deaths exceeds model population (N)")
            }
            #if prob of death  = 0
            if(epiModel@odinModel$contents()$pDeath == 0){
              stop("Since there is no chance of death in this model, it cannot
                   be fit using death data.")
            }
            #Assigning the total number of deaths
            epiModel@currentState$D <- totalDeaths
            #Get model parameters
            Alpha <- epiModel@odinModel$contents()$alpha
            Gamma <- epiModel@odinModel$contents()$gamma
            #Calculate the number of recoveries
            epiModel@currentState$R <- totalDeaths * Gamma/Alpha
            return(epiModel)
          }
)
