#' An S4 method to calculate current state of R and D for an SIR when provided
#' with a time-series of deaths
#'
#' Please note that this method does not guarantee that this state would be
#' generated by the model, given its initial conditions.
#' Calculates the number of people in the recovered state by scaling D by the
#' rate of recovery divided by the rate of death.
#' These values are then stored in the list in the slot "currentState".
#'
#' @param epiModel The epidemic model of class SIR to have the current state of
#' R and D calculated.
#' @param deaths A time-series of the cumulative death counts for this model.
#' @return An object of class sirModel with the values for D and R updated
#' for the current state.
#' @examples
#' #create example model
#' model <- setSIR(N = 100, Beta = 1, Gamma = 1/5, ProbOfDeath = 0.5, I0 = 1)
#' #Set the deaths (only one entry is required)
#' deaths <- c(10,20)
#' #call this function
#' model <- excalibur::calculateDownstreamExponentialNodes(model, deaths=deaths)
#'
#' print(model@currentState$D)
#' print(model@currentState$R)
#' @export
setMethod("calculateDownstreamExponentialNodes", signature("sirModel"),
          function(epiModel, deaths){
            totalDeaths <- deaths[length(deaths)]
            #check for errors
            sir_Methods_errorChecks(epiModel, deaths, totalDeaths)
            #Assigning the total number of deaths
            epiModel@currentState$D <- totalDeaths
            #Get model parameters
            Alpha <- epiModel@odinModel$contents()$alpha
            Gamma <- epiModel@odinModel$contents()$gamma
            #Calculate the number of recoveries
            epiModel@currentState$R <- totalDeaths * Gamma/Alpha
            return(epiModel)
          }
)
#' An S4 method to estimate current state of S and I for an SIR when provided
#' with a time-series of deaths
#'
#' Please note that this method does not guarantee that this state would be
#' generated by the model, given its initial conditions.
#' At the present this model assumes a difference equation set-up to calculate
#' the number of infected/susceptible and so will be close to but not the same
#' as the result from an equivalent differential equations model.
#' These values are then stored in the list in the slot "currentState".
#'
#' @param epiModel The epidemic model of class SIR to have the current state of
#' S and I estimated.
#' @param deaths A time-series of the cumulative death counts for this model.
#' @return An object of class sirModel with the values for S and I updated
#' for the current state.
#' @examples
#' #create example model
#' model <- setSIR(N = 100, Beta = 1, Gamma = 1/5, ProbOfDeath = 0.5, I0 = 1)
#' #Set the deaths (only one entry is required)
#' deaths <- c(10,20)
#'
#' #call this + the D+R node function
#' model <- calculateCurrentState(model, deaths=deaths)
#'
#' #check S and I
#' currentState(model)
#' @export
setMethod("estimateInfectiousNode", signature("sirModel"),
          function(epiModel, deaths){
            warning("This currently assumes difference equation framework,
                    during testing this has led to error from the true sizes
                    of I and S as large as 10%, when extreme values of
                    Beta and Gamma are used")
            #check for errors in death specification
            sir_Methods_errorChecks(epiModel, deaths, deaths[length(deaths)])
            #additional check
            if(length(deaths) < 2){
              stop("There must be at least 2 observations in deaths from different
                   time-points")
            }
            #get model parameters
            parameters <- epiModel@odinModel$contents()
            Alpha <- parameters$alpha
            Gamma <- parameters$gamma
            Beta <- parameters$betas
            changeTimes <- parameters$ct
            N <- parameters$S0 +
              parameters$I0 +
              parameters$R0 +
              parameters$D0
            #derive number changes to R via rates
            recoveries <- deaths*Gamma/Alpha
            #calculate changes from previous time to now
            newD <- diff(deaths)[length(deaths) - 1]
            newR <- diff(recoveries)[length(recoveries) - 1]

            ##Assume Difference model, Adhoc to be changed?
            #convert rates to probabilities/risks
            pAlpha <- rateToRisk(Alpha)
            pGamma <- rateToRisk(Gamma)
            ## risk of infection depends on size of I
            #calculate I at time-1 using new deaths + new recoveries
            Iprev <- (newR + newD)/(1-(1-pGamma)*(1-pAlpha))
            #Calculate S and R at time - 1
            Dprev <- deaths[length(deaths)-1]
            Rprev <- Dprev * Gamma/Alpha
            Sprev <- N - Iprev - Dprev - Rprev
            #calculate I at time by propagating forwards
            I <- Iprev*(1-pGamma)*(1-pAlpha) + #proportion not going to R+D
              rateToRisk(Beta*Iprev/N)*Sprev #new infections
            #calculate S
            S <- N - I - epiModel@currentState$R - epiModel@currentState$D
            #assign to list
            epiModel@currentState$I <- I
            epiModel@currentState$S <- S
            return(epiModel)
          }
)
#' Internal function to run repeat error checks for the SIR methods
#' @noRd
sir_Methods_errorChecks <- function(epiModel, deaths, totalDeaths){
  #checking deaths are in the correct format
  if(any(deaths > totalDeaths) |
     !is.numeric(deaths)){
    stop("deaths must be a numeric timeseries of the cumulative number of
                   deaths. The time between each update should be the unit time
                   for the parameters.")
  }
  #checking there are not more deaths than people in model
  if(totalDeaths > epiModel@odinModel$contents()$S0 +
     epiModel@odinModel$contents()$I0 +
     epiModel@odinModel$contents()$R0 +
     epiModel@odinModel$contents()$D0){
    stop("deaths exceeds model population (N)")
  }
  #if prob of death  = 0
  if(epiModel@odinModel$contents()$pDeath == 0){
    stop("Since there is no chance of death in this model, it cannot
                   be fit using death data.")
  }
}

